
INSERT INTO dados_jogo(descricao, loja, nome_do_jogo, nota, preco, url_imagem) VALUES('Incrível!!', 'Amazon', 'DixIt', 10, 279.99, 'https://images-na.ssl-images-amazon.com/images/I/71v70BVCqGL.__AC_SX300_SY300_QL70_ML2_.jpg');
INSERT INTO dados_jogo(descricao, loja, nome_do_jogo, nota, preco, url_imagem) VALUES('Muito bom com os amigos!', 'Amazon', 'Black Stories', 8, 43.87, 'https://m.media-amazon.com/images/I/61-zbcN6HmL._AC_SY879_.jpg');
INSERT INTO dados_jogo(descricao, loja, nome_do_jogo, nota, preco, url_imagem) VALUES('Muito complicado, mas aprendendo fica bom!', 'Amazon', 'Magic', 7, 229.9, 'https://m.media-amazon.com/images/I/61zEBPUEp-L._AC_SX569_.jpg');
INSERT INTO dados_jogo(descricao, loja, nome_do_jogo, nota, preco, url_imagem) VALUES('Clássico', 'Americanas', 'Dectetive', 8, 99.99, 'https://m.media-amazon.com/images/I/91deu+m93jL._AC_SX569_.jpg');
INSERT INTO dados_jogo(descricao, loja, nome_do_jogo, nota, preco, url_imagem) VALUES('Pura nostalgia!!', 'Americanas', 'Banco Imobiliario', 10, 163, 'https://http2.mlstatic.com/D_NQ_NP_815831-MLA46818901945_072021-O.webp');
INSERT INTO dados_jogo(descricao, loja, nome_do_jogo, nota, preco, url_imagem) VALUES('Bem divertido', 'Americanas', 'Banco Imobiliario Mundo', 7, 139, 'https://http2.mlstatic.com/D_NQ_NP_989487-MLB41695008984_052020-O.webp');
INSERT INTO dados_jogo(descricao, loja, nome_do_jogo, nota, preco, url_imagem) VALUES('Siniiiisxxxxxtroooo....', 'Amazon', 'Zombicide: Black Plague', 10, 799.99, 'https://m.media-amazon.com/images/I/81bBS06A9LL._AC_SX569_.jpg');
INSERT INTO dados_jogo(descricao, loja, nome_do_jogo, nota, preco, url_imagem) VALUES('Bons tempos de rpg', 'Mercado Livre', 'Hero Quest', 6, 17.71, 'https://http2.mlstatic.com/D_NQ_NP_881688-MLB45649029491_042021-O.webp');
INSERT INTO dados_jogo(descricao, loja, nome_do_jogo, nota, preco, url_imagem) VALUES('Excepcional, nunca vi um jogo assim!', 'Amazon', 'Gloomhaven', 10, 1329, 'https://m.media-amazon.com/images/I/51mmjCK-PiL._AC_.jpg');
INSERT INTO dados_jogo(descricao, loja, nome_do_jogo, nota, preco, url_imagem) VALUES('Muito fiel a série', 'Amazon', 'Guerra dos Tronos', 8, 317, 'https://m.media-amazon.com/images/I/A105putUJ4L._AC_SX569_.jpg');
INSERT INTO dados_jogo(descricao, loja, nome_do_jogo, nota, preco, url_imagem) VALUES('Mais um clássico dos anos 80!', 'RiHappy', 'WAR', 7, 209.9, 'https://a-static.mlcdn.com.br/800x600/title-reference/magazineluiza/220544300/a1fde1e72b47f486c040667c5ce7183a.jpg');